version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: catalogo_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: catalogo_virtual
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ../01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql:ro
      - ../02_insert_db_grupob04.sql:/docker-entrypoint-initdb.d/02_insert_db_grupob04.sql:ro
volumes:
  db_data: